"""Lightweight project hygiene scanner used by diagnostics and release checks."""
from __future__ import annotations

import ast
import os
from pathlib import Path
from typing import Any, Dict, Iterator, List

# Directories generated by tools/dependencies must not be scanned as project source.
# Important: virtual environments contain thousands of cache/bytecode files;
# those are valid dependency artifacts and must not block local startup.
EXTERNAL_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "env",
    "node_modules",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "dist",
    "build",
}
DATA_DIRS = {"data", "instance", "uploads"}
GENERATED_DIRS = {"__pycache__"}
MARKER_WORDS = ("TO" + "DO", "FIX" + "ME")


def _is_ignored(rel_parts: tuple[str, ...]) -> bool:
    """Return True for dependency/runtime/generated paths that are not app source."""
    return any(part in EXTERNAL_DIRS or part in DATA_DIRS for part in rel_parts)


def _walk_project_files(root: Path) -> Iterator[Path]:
    """Yield files while pruning dependency/runtime directories before descent."""
    root = Path(root)
    skip_dirs = EXTERNAL_DIRS | DATA_DIRS | GENERATED_DIRS
    for dirpath, dirnames, filenames in os.walk(root):
        current = Path(dirpath)
        rel_parts = current.relative_to(root).parts if current != root else ()
        if _is_ignored(rel_parts) or any(part in GENERATED_DIRS for part in rel_parts):
            dirnames[:] = []
            continue
        dirnames[:] = [name for name in dirnames if name not in skip_dirs]
        for filename in filenames:
            yield current / filename


def _iter_source_files(root: Path) -> Iterator[Path]:
    """Yield project files while skipping dependency and runtime trees.

    Generated bytecode/cache folders are intentionally skipped during local
    diagnostics. A user should never be blocked from starting the backend just
    because Python created bytecode after imports.
    """
    yield from _walk_project_files(Path(root))


def _iter_forbidden_release_artifacts(root: Path) -> Iterator[Path]:
    """Find release artifacts in source-controlled paths only.

    Unlike source scanning, this intentionally reports project-local bytecode as
    a warning. Dependency, data, and build trees are pruned before descent so a
    local virtualenv never makes the checker slow.
    """
    root = Path(root)
    skip_dirs = EXTERNAL_DIRS | DATA_DIRS
    for dirpath, dirnames, filenames in os.walk(root):
        current = Path(dirpath)
        rel_parts = current.relative_to(root).parts if current != root else ()
        if _is_ignored(rel_parts):
            dirnames[:] = []
            continue
        dirnames[:] = [name for name in dirnames if name not in skip_dirs]
        in_generated = any(part in GENERATED_DIRS for part in rel_parts)
        for filename in filenames:
            path = current / filename
            if in_generated or path.suffix == ".pyc":
                yield path


def scan_project(root: Path | str) -> Dict[str, Any]:
    """Return a concise, deterministic code-cleanliness report.

    Fatal status is reserved for syntax errors because those can break imports.
    Release hygiene issues such as bytecode files, very large modules, and
    marker comments are exposed as warnings so local startup does not fail.
    """
    root = Path(root)
    python_files: List[Path] = []
    syntax_errors: List[Dict[str, str]] = []
    oversized: List[Dict[str, Any]] = []
    markers: List[Dict[str, Any]] = []
    forbidden_artifacts: List[str] = []

    for artifact in _iter_forbidden_release_artifacts(root):
        forbidden_artifacts.append(artifact.relative_to(root).as_posix())

    for path in _iter_source_files(root):
        rel = path.relative_to(root).as_posix()
        if path.suffix != ".py":
            continue

        python_files.append(path)
        text = path.read_text(encoding="utf-8", errors="replace")
        try:
            ast.parse(text, filename=rel)
        except SyntaxError as exc:
            syntax_errors.append({"file": rel, "line": str(exc.lineno or "?"), "error": exc.msg})
            continue

        line_count = text.count("\n") + 1
        if line_count > 1800:
            oversized.append({"file": rel, "lines": line_count, "recommendation": "split when touching this area again"})

        for idx, line in enumerate(text.splitlines(), 1):
            upper = line.upper()
            if any(word in upper for word in MARKER_WORDS):
                markers.append({"file": rel, "line": idx, "text": line.strip()[:160]})

    warning_count = len(forbidden_artifacts) + len(oversized) + len(markers)
    status = "fail" if syntax_errors else ("warn" if warning_count else "pass")
    return {
        "status": status,
        "fatal": bool(syntax_errors),
        "python_files": len(python_files),
        "syntax_errors": syntax_errors,
        "forbidden_artifacts": forbidden_artifacts[:200],
        "oversized_modules": oversized,
        "markers": markers[:50],
        "summary": {
            "syntax_error_count": len(syntax_errors),
            "forbidden_artifact_count": len(forbidden_artifacts),
            "oversized_module_count": len(oversized),
            "marker_count": len(markers),
            "warning_count": warning_count,
        },
    }
